name: Deploy to GitHub Pages with Version Update

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Update Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest project tag
        id: get_project_tag
        run: |
          PROJECT_REPO="VelixDevelopments/Imperat" # REPLACE THIS
          response=$(curl -s -H "Accept: application/vnd.github+json" "https://api.github.com/repos/$PROJECT_REPO/releases/latest")
          LATEST_PROJECT_TAG=$(echo "$response" | jq -r '.tag_name')
          echo "LATEST_PROJECT_TAG=$LATEST_PROJECT_TAG" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Replace version placeholder
        run: |
          PROJECT_VERSION="${{ env.LATEST_PROJECT_TAG }}"
          DOCS_DIR="./docs" # Adjust if needed
          find "$DOCS_DIR" -name "*.md" -print0 | while IFS= read -r -d $'\0' file; do
            sed -i "s/{version}/$PROJECT_VERSION/g" "$file"
          done

      - name: Build website
        env:
          PROJECT_VERSION: ${{ env.LATEST_PROJECT_TAG }}
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
